### ISSUE TITLE
HH:MM vs HH.XX (minutes vs fractional hours)

### ISSUE THREAD

**Issue by bladedvox** [mrusme/zeit#13]
In individual entries `zeit` uses the `HH:MM` format, but in totals it uses `HH.XX` where `XX` is from `00` to `99`.

On my own system I at least modified the total given by `zeit list --total` to show `HH:MM` but I wonder if you would be receptive to an option to choose one format or the other or just using `HH:MM` everywhere to reduce confusion?

**Comment by mrusme** [comment]
@bladedvox good point! Do you happen to have a PR? :-)

**Comment by bladedvox** [comment]
No PR yet as I wanted some input before starting a real effort on it. Would a flag in the database to set the preferred output be desirable? Then we could just wrap all the duration outputs in a function that checks the flag before outputting one format or the other?

**Comment by mrusme** [comment]
Hm, not sure about the database. I believe having a default set in code and the ability to change that with a flag should be good enough, wdyt? `HH:MM` is fine for me. :-)

**Comment by bladedvox** [comment]
Ok, then; `HH:MM` by default with a command line flag to choose fractional hours for the weirdos out there :) I will work on it when my free time permits!
