### ISSUE TITLE
Checksum mismatch

### ISSUE THREAD

**Issue by miltkall** [mrusme/zeit#17]
Hello @mrusme,

great software! I am considering contributing some extra features in the near future.  

At the moment I am creating an AUR package, yet the md5sum does not match with the one you provide in your releases  e.g. the [zeit_0.0.6_checksums.txt](https://github.com/mrusme/zeit/releases/download/v0.0.6/zeit_0.0.6_checksums.txt) 

**Running:** 
`md5sum ~/zeit_0.0.6_linux_amd64.tar.gz` results to: 
`12468fd10159f9e4c58ac81bda5f8607` 
and **not** 
`9e257949c9406179c88827493eb311eb8c8a7a70f23062e47dbc478511e01e86` (the one you provide in your zeit_0.0.6_checksums.txt).

Are you aware of that? 

I have not do this before. If there is another command for this operation you can post it, below, thanks.

**Comment by mrusme** [comment]
Hey @miltkall,

thank you for the initiative to contribute to this project! You're very welcome to do so.

As for this specific issue, it's just a bit of confusion on your end I believe:

```sh
$ sha256sum zeit_0.0.6_linux_amd64.tar.gz | xargs -I {} rg "{}" zeit_0.0.6_checksums.txt
18:9e257949c9406179c88827493eb311eb8c8a7a70f23062e47dbc478511e01e86  zeit_0.0.6_linux_amd64.tar.gz
```

Feel free to double check on your local machine and re-open if you should find that any of the checksums do not match.

**Comment by miltkall** [comment]
Hello again, 

you are right! I used md5sum. Next time I know.

I will keep you posted for new features. I am now reading your code. Thanks for your time. Talk you soon ...
