### ISSUE TITLE
More user friendly time formats

### ISSUE THREAD

**Issue by harnoorsaini** [mrusme/zeit#18]
Hello, thanks for this tool.
I am trying to easily get a sum for my daily project/task (I only have 1). 
But "zeit list", breaks it down into multiple chunks during the day (since I stop it when I go for lunch). 
It would be nice to do something like "zeit list --since today --total" . Perhaps also "yesterday" or "this week". Thanks!

**Comment by harnoorsaini** [comment]
Never mind, I was just being lazy I guess. After about 10 minutes I solved my own problem (at least for the current day). For anyone else:
zeit list --since "$(date +%F)T01:00:00+18:00" --total
Alias that and you are good to go.

**Comment by mrusme** [comment]
@harnoorsaini if you would like to feel free to PR and update to the README with a *Tips and Tricks* section and add your aliases there, with short comments explaining what they do. :-)

**Comment by harnoorsaini** [comment]
@mrusme sure, will try and do it over the next couple of days.
