### ISSUE TITLE
Question database.go software implementation

### ISSUE THREAD

**Issue by miltkall** [mrusme/zeit#20]
Hello there,
I have beeen reading/understanding your code in order to implement some new features. On these [lines](https://github.com/mrusme/zeit/blob/446865a19c193e4656116d6e48b3e2de01bf4d3c/z/database.go#L29) your create some DB indexes. 

Do you actually use them somewhere (you only use AscendKeys in order to access the DB)?

Moreover you use AscendKeys [here](https://github.com/mrusme/zeit/blob/master/z/database.go#L74) and [here](https://github.com/mrusme/zeit/blob/master/z/database.go#L167), when you only expect one result. Could this get implemented with a tx.Get method? 

Of course the software works, I am just doing constructive criticms and trying to create a new feature 😄 so not a true issue...

Many thanks!

**Comment by mrusme** [comment]
Hey there!

> On these [lines](https://github.com/mrusme/zeit/blob/446865a19c193e4656116d6e48b3e2de01bf4d3c/z/database.go#L29) your create some DB indexes.
>
> Do you actually use them somewhere (you only use AscendKeys in order to access the DB)?

Not yet. I planned to do so initially, but all queries turned out differently than anticipated. The indexes should probably be updated to work with the existing queries - or the querying should be refactored in general, since ...

> Moreover you use AscendKeys [here](https://github.com/mrusme/zeit/blob/master/z/database.go#L74) and [here](https://github.com/mrusme/zeit/blob/master/z/database.go#L167), when you only expect one result. Could this get implemented with a tx.Get method?

... it's not *ideal*. :-) You're totally right here, lots of room for improvement!

Let me know if you need further info!

**Comment by miltkall** [comment]
Thanks for your fast response.

1. "the querying should be refactored in general" I could implement it, if you have concrete suggestions.

2. "You're totally right here, lots of room for improvement!" Should I make a pull request using the tx.Get method?

**Comment by mrusme** [comment]
> I could implement it, if you have concrete suggestions.

Tbh I don't, mainly because I haven't checked the recent versions of buntdb to see if/what's new, especially in regard of querying. In general I'd look for ways to optimize querying of large datasets, which goes back to indexes and maybe segmentation of data.

> Should I make a pull request using the tx.Get method?

Sure! 👍🏼

**Comment by miltkall** [comment]
For example [here](https://github.com/mrusme/zeit/blob/master/z/database.go#L195) you sort the slice after you extract the data from the DB. The DB could do that for us if we restructure the data. 

Should I give it a try?

**Comment by mrusme** [comment]
@miltkall thanks for checking back, yes, sure, feel free! :-)
