### ISSUE TITLE
Feature: Simpler begin/finish update for an entry

### ISSUE THREAD

**Issue by miltkall** [mrusme/zeit#23]
Many times you just want to do +/- 20/30min of the `begin/finish`  on a task, but you do not want to format the time you just want to:

`zeit entry --begin -10 {{TASK_ID}}`

Should I implement it ? Do you have any suggestions? Many thanks 😇

**Comment by mrusme** [comment]
Sounds good, how would you go about if someone wanted to subtract or add, let's say, one hour and ten minutes? `-70`? Or would that be `-1:10`?
