### ISSUE TITLE
Feature: Implement day stats

### ISSUE THREAD

**Issue by miltkall** [mrusme/zeit#24]
I have never used timewarrior, but their output looks interesting:

![image](https://user-images.githubusercontent.com/7304125/188270097-b7ff48c1-ac1e-4085-b4d7-b1767e2d1167.png)

Should I implement something similar? Any suggestions on how to generate such output? 

Many thanks 😇

**Comment by mrusme** [comment]
Heh, good that you're asking, thank you! :-) I was intending to rewrite and extend the visualization stuff at some point.

My thoughts were as following:

- Take the existing visualization code (the poor-man's graphs I manually implemented) and rewrite them nicely as part of [lipgloss](https://github.com/charmbracelet/lipgloss) or [Bubbletea](https://github.com/charmbracelet/bubbletea) or [Bubbles](https://github.com/charmbracelet/bubbles) -- I'm confused myself here, so I'd probably check back with @meowgorithm about this first to make sure it lands in the correct repo
- Then, when it's implemented into lipgloss/bubbletea/bubbles, take that library and use it in `zeit`

Hence, regarding your suggestion: I love it. However, I don't think it's `zeit` that should implement it/receive a PR for this, but rather libgloss/bubbletea/bubbles. :-)

**Comment by selfire1** [comment]
Hi! I've been using Zeit for a while now and the no-fuss `zeit stats` is what drew me to it in the beginning. I'm not familiar with Go, so I couldn't contribute but just wanted to chime in that I'd love some more visualisation options. The two week overview is great, so supporting longer or shorter timeframes would be fantastic!
