### ISSUE TITLE
Create tests

### ISSUE THREAD

**Issue by miltkall** [mrusme/zeit#25]
I could gladly write some tests. What do you think? 

Could you make some suggestions on what to test? 

Looking forward ... 🙃

**Comment by mrusme** [comment]
While I think tests are beneficial in general, so far `zeit` is mainly doing simple CRUD operations, with a few range loops here and there. Surely these could fail at some point so it makes sense to put tests in place as soon as the code base stabilizes.

If you feel like there are places in the code that seem fragile or overly complex, feel free to add a few unit tests if you'd like. :)
