### ISSUE TITLE
[IMPROVEMENT] Remove unneccessary verbose boolean checks. 

### ISSUE THREAD

**Issue by MaximilianSoerenPollak** [mrusme/zeit#33]
When I looked through the code I saw quite a few places where there was some checks made that are not neccessary in that 'verbosity'. 

Examples of said verbosity here: 

```go
if since.IsZero() == false && since.Before(entry.Begin) == false && since.Equal(entry.Begin) == false {
  continue
}
```
Could be simplified to: 
```go 
if !since.IsZero() && !since.Before(entry.Begin) && !since.Equal(entry.Begin) {
  continue
}
```

Now my question would be, is this verbosity explicitly wanted or would this be something that one could remove and simplify via a PR? 

Please let me know.

**Comment by MaximilianSoerenPollak** [comment]
I don´t mind either, only thing is that 'linters' and some static checkers will complain if you would have them on. 
But if it was an intentional decision then I don´t think we need to change this.

I don´t know what's more `idiomatic` in Go, but then again that word has been used to mean anything and everything. :rofl:

**Comment by mrusme** [comment]
If you would dare to turn on a linter it would probably go brrrrrrrrrr anyway, due to me having used two spaces for indentation. (-:
